services:
  - type: web
    name: websocket-server
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: tsx ws-server.ts
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://hcmut-tutor.vercel.app
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

